# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f08710af6796a2767ea967b93a29f156bcb030be2ee805bce15a6b8f4d9844904a29b3ba5909de01cfcf55632d285cf4121050d1027058a821010a205d547a

test:
  secret_key_base: 16dc19b017b6448ca1ed4be32eddf62aaba3f75fab13794016a4778d92c3804065ea9b922131f6466b0c22e0fc7e2db319d5955b3a45d542c5773432929e5ba0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
